### ISSUE TITLE
ERROR - Can not locate the barcodes.tsv file!

### ISSUE THREAD

**Issue by chrismahony** [velocyto-team/velocyto.R#183]
Hi

I am running hte following:

source my-virtual-env-${BB_CPU}/bin/activate

velocyto run10x /path/FASTQ/CON_A/Align/CON_A \
                 /path/mm10/Mus_musculus.GRCm39.105.gtf

but I get the following error:
2022-03-15 16:04:06,583 - ERROR - Can not locate the barcodes.tsv file!
Traceback (most recent call last):
  File "/rds/homes/m/mahonyc/.local/bin/velocyto", line 8, in <module>
    sys.exit(cli())
  File "/rds/bear-apps/2021a/EL8-cas/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/rds/bear-apps/2021a/EL8-cas/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/rds/bear-apps/2021a/EL8-cas/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/rds/bear-apps/2021a/EL8-cas/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/rds/bear-apps/2021a/EL8-cas/software/Python/3.9.5-GCCcore-10.3.0/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/rds/homes/m/mahonyc/.local/lib/python3.9/site-packages/velocyto/commands/run10x.py", line 91, in run10x
    bcfile = bcmatches[0]
IndexError: list index out of range

If you could help I would really appreciate it, thanks,
Chris

**Comment by chrismahony** [comment]
my barcodes file is in CON_A>outs>filtered_feature_bc_matrix

I have tried putting it in other places, but I still get the same error?

**Comment by Sa753** [comment]
I am getting the same error as well when I run it on the output of cellranger multi?. Did you solve this issue please?

Thanks

**Comment by ganpha** [comment]
Hello, I have the same issue with cellranger multi output. I tried giving the full path to the barcodes.tsv file, but it gives error - "Can not locate the barcodes.tsv file!"  Can anyone help resolve this issue? Thanks!

**Comment by pushpinder-bu** [comment]
Hi, I am having the same issue. Any idea how to run it with cellranger multi output?
